apiVersion: v1
kind: ConfigMap
metadata:  
  name: ms-travel-website
  namespace: dev
  labels:    
    project.app: ms-travel-website
    project.name: ms-travel-website
data:
  application.properties: |-
    spring.application.name=ms-travel-website
    travel.service.destination=Dallas
    travel.service.source=DC
    new.config=sample