apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:  
  name: ms-travel-website
  namespace: dev
  labels:    
    project.app: ms-travel-website
    project.name: ms-travel-website
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: ms-travel-website
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70